name: Geração e Publicação de Conteúdo

on:
  schedule:
    - cron: '0 12,21 * * *' # 09:00 e 18:00 BRT
  workflow_dispatch:

jobs:
  gerar-publicar:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
      IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
      IG_BUSINESS_ID: ${{ secrets.IG_BUSINESS_ID }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r backend/requirements.txt
      - name: Run scheduler (gera e envia para Telegram)
        run: python backend/scheduler.py &
      - name: Commit posts aprovados
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "Mamae Bot"
          git add site/content/posts/
          git commit -m "Novo post aprovado" || echo "Nada para commitar"
          git push
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.124.1'
      - name: Build site
        run: cd site && hugo
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: './site/public'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
